name: tm_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - lxml
  - numpy
  - pandas
  - python-dotenv
  - spyder
  - pip
  - pip:
      - nlpcloud
      - sentence-transformers
